### ISSUE TITLE
Bug: Extension doesn't auto-adjust width of the column as per the title.

### ISSUE THREAD

**Issue by Droyk** [Terrance/Homely#11]
I know this has been reported before #7. But it hasn't been fixed yet.
![Annotation 2019-04-27 152736](https://user-images.githubusercontent.com/15848350/56848346-74fcfa80-6905-11e9-8754-a16fc53f2de4.png)

temp fix is adding this code `#links .btn {
  white-space: normal;
}` to the custom css in settings.

I know that's an easy fix however I use multiple computers, So I am tired of doing this over & over again. 
Dev, plz fix this.

**Comment by Terrance** [comment]
> I know this has been reported before #7

Then please comment there instead of opening a duplicate.  The linked issue included a fix for this, and it seems to work fine here:

![image](https://user-images.githubusercontent.com/4025899/56860930-ca7fe880-6993-11e9-9159-286a835f8f34.png)
