### ISSUE TITLE
Feature Request: RSS support

### ISSUE THREAD

**Issue by Droyk** [Terrance/Homely#15]
Man, I really miss the RSS support from My previous new tab page & that's the only feature missing from this extension.

this feature is super useful. it wouldn't only increase your user base but will also make your extension more robust & enhance user experience.

Implementation 

![2019-05-05_8-25-30](https://user-images.githubusercontent.com/15848350/57188174-d598c280-6f17-11e9-8120-d35a1055b980.png)
Forgive me for a really bad presentation.

**Comment by Terrance** [comment]
Too big a change and not something I want to put the time into (there be dragons in parsing RSS feeds, getting the web permissions to retrieve a given feed without access to any URLs etc.), but I'd consider a PR if one came about.

**Comment by Droyk** [comment]
😔😟😢😭
