### ISSUE TITLE
homely not working in invisible mode

### ISSUE THREAD

**Issue by Jack2code** [Terrance/Homely#16]
when i open a new tab in invisible mode, the homely plugin doesn't work. It shows the default page, not the homely page.

**Comment by Terrance** [comment]
Changed recently?  If so then probably to do with changes for Firefox compatibility (though the Chrome docs don't mention anything about interop between incognito mode and new tab page overrides); if not then Chrome might have changed something.

**Comment by Jack2code** [comment]
It's Chrome. version :74.0.3729.131

**Comment by Jack2code** [comment]
Homely version is 1.7.2

**Comment by Terrance** [comment]
If Chrome has changed their behaviour to prevent overriding the incognito new tab page then it's unlikely there's much we can do about it.  Firefox already appears to prevent this behaviour.
