### ISSUE TITLE
Suggestion: Search function to quickly search the links.

### ISSUE THREAD

**Issue by Droyk** [Terrance/Homely#19]
I have many columns with many links & sometimes it's hard for me to remember where to look, all the more when they are inside a menu. so just for the sake of convenience, I would love to see a search function that lets me search links by their title, domain, by the name of the menu, etc.

**Comment by Terrance** [comment]
Chrome already has search in the omnibox -- assuming you've been to each of your links at least once, they should come up on a search by either title or domain.  If you need more structured searching, you're probably better bookmarking and searching by bookmarks, which can be searched either from the omnibox or within Homely's bookmarks panel.  Seems unnecessary to reimplement what Chrome is already designed to do well.
