### ISSUE TITLE
Missing a simular extention to Atlassian Confluence, any plans for porting it to Confluence as an plugin ?

### ISSUE THREAD

**Issue by borrenordbakken** [Terrance/Homely#22]

**Comment by Terrance** [comment]
I don't really see the need for it -- Confluence has a WYSIWGY editor so it wouldn't be overly difficult to just create a table of links in a similar layout, foregoing the dropdowns.  I've only used Confluence as an end-user so I've no idea what the plugin structure is like, but code sharing of logic beyond links would be unlikely given Homely makes client-side requests that won't work outside of a browser extension.  The code is here if anyone wants to use it as a base for something like that, but it's not something I'll be taking on.
