### ISSUE TITLE
Feature request: change top bar color

### ISSUE THREAD

**Issue by valbadalejo** [Terrance/Homely#29]
Hello,
As you see in the screenshot, it may be nice if we could choose the color of the top bar and the links blocks.
Or is there already a specific code to do so?
Thank you!

![Captura de pantalla de 2023-10-15 09-58-36](https://github.com/Terrance/Homely/assets/141549965/1f25d4ba-95d3-49d9-8ec1-2d279d1c570c)

**Comment by Terrance** [comment]
Settings > Customise > Style -- the link blocks you can change via _Panel style_, the bar you can toggle between light and dark with _Use dark bar_.
