### ISSUE TITLE
How to export / import homely.json

### ISSUE THREAD

**Issue by TimFH** [Terrance/Homely#30]
At one point during setup of Homely I was given the option to export / import my customizations as a json file, but now that I've gotten things setup and would like to export my customizations from Chrome to Brave, I can't seem to find a way to do this (there is nothing about it in Settings that I can see). Please advise.

**Comment by Terrance** [comment]
These?

![image](https://github.com/Terrance/Homely/assets/4025899/1378f7f2-aab1-4fc9-b8dc-cdf03f200360)

**Comment by TimFH** [comment]
Yes, that's what the Settings menu looks like when you first install Homely, but now there's NO MENTION of "Customize" let alone Import/Export from/to file: 

![image](https://github.com/Terrance/Homely/assets/8481426/5b882f48-51fa-4893-9731-0c5d993b6333)

**Comment by Terrance** [comment]
That settings screen is nothing to do with Homely -- is that Chrome/Brave's own settings, or that of a different extension you have installed that also wants to be the new tab page?

The settings menu I showed above appears within Homely itself, on the right side of the top bar.  If you're not looking at Homely as the new tab page then you're in the wrong place.
